// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDi-wF2u8JOKzXN9-OHAwCR46y9M97TgrA',
    appId: '1:1042769401900:web:e130d1d5fd01dfe0c35989',
    messagingSenderId: '1042769401900',
    projectId: 'airshero-b81e4',
    authDomain: 'airshero-b81e4.firebaseapp.com',
    storageBucket: 'airshero-b81e4.firebasestorage.app',
    measurementId: 'G-CCL1E998H4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3C6Ei0NEh1QD3OlZnNl0xuepvkaWZjaU',
    appId: '1:1042769401900:android:c4ad56c7b8cbe73fc35989',
    messagingSenderId: '1042769401900',
    projectId: 'airshero-b81e4',
    storageBucket: 'airshero-b81e4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_HBiftKSddVyGOzywTrmBfeh8T1T9XkM',
    appId: '1:1042769401900:ios:100171280298d452c35989',
    messagingSenderId: '1042769401900',
    projectId: 'airshero-b81e4',
    storageBucket: 'airshero-b81e4.firebasestorage.app',
    iosBundleId: 'com.example.airsherof',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC_HBiftKSddVyGOzywTrmBfeh8T1T9XkM',
    appId: '1:1042769401900:ios:100171280298d452c35989',
    messagingSenderId: '1042769401900',
    projectId: 'airshero-b81e4',
    storageBucket: 'airshero-b81e4.firebasestorage.app',
    iosBundleId: 'com.example.airsherof',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDi-wF2u8JOKzXN9-OHAwCR46y9M97TgrA',
    appId: '1:1042769401900:web:b4b781ba219d7091c35989',
    messagingSenderId: '1042769401900',
    projectId: 'airshero-b81e4',
    authDomain: 'airshero-b81e4.firebaseapp.com',
    storageBucket: 'airshero-b81e4.firebasestorage.app',
    measurementId: 'G-KSK7Y3NFHE',
  );
}
